name: Lint
on:
    push:
    workflow_dispatch:
    schedule:
        - cron: "30 12 * * *" # 30 minutes before Dependabot

permissions: write-all

jobs:
    format:
        name: Format
        if: ${{ always() }}
        runs-on: ubuntu-20.04

        steps:
            - name: Checkout
              uses: actions/checkout@v3.5.2
              with:
                  ref: ${{ github.head_ref }}

            - name: Setup Node.JS
              uses: actions/setup-node@v3.6.0
              with:
                  node-version: "18.12.1"
                  cache: "npm"

            - name: Install
              run: npm ci

            - name: Format
              run: npm run format

            - name: Commit
              uses: stefanzweifel/git-auto-commit-action@8621497c8c39c72f3e2a999a26b4ca1b5058a842 # v5.0.1
              with:
                  commit_message: Format
                  branch: ${{ github.head_ref }}

    build:
        name: Build
        if: ${{ always() }}
        runs-on: ubuntu-20.04

        steps:
            - name: Checkout
              uses: actions/checkout@v3.5.2
              with:
                  ref: ${{ github.head_ref }}

            - name: Setup Node.JS
              uses: actions/setup-node@v3.6.0
              with:
                  node-version: "18.12.1"
                  cache: "npm"

            - name: Install
              run: npm ci

            - name: Build
              run: npm run build
